name: Gutentag, World!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - name: Run
        run: julia -e "using GutentagWorld; println(gutentag_world())"

      - name: Verify output
        run: bash test.sh
